dbshzbv

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -60,7 +60,7 @@ jobs:
         uses: actions/cache@v4
         with:
           path: |
-            .next/cache
+            ../.next/cache
           key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
           restore-keys: |
             ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
@@ -82,13 +82,13 @@ jobs:
         run: ls -la
 
       - name: List .next directory contents
-        run: ls -la ./.next || echo ".next directory not found"
+        run: ls -la ../.next || echo ".next directory not found"
 
       - name: Upload artifact
         if: success()
         uses: actions/upload-pages-artifact@v3
         with:
-          path: ./.next
+          path: ../.next
 
   deploy:
     environment:
@@ -102,4 +102,4 @@ jobs:
         uses: actions/deploy-pages@v4
         with:
             github_token: ${{ secrets.GITHUB_TOKEN }}
-            publish_dir: ./.next
+            publish_dir: ../.next
